# Generated by Django 4.2 on 2023-05-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommembers',
            options={'verbose_name_plural': 'RoomMembers'},
        ),
    ]
